# Form implementation generated from reading ui file 'ui/orderframe.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderFrame(object):
    def setupUi(self, OrderFrame):
        OrderFrame.setObjectName("OrderFrame")
        OrderFrame.resize(592, 289)
        self.horizontalLayout = QtWidgets.QHBoxLayout(OrderFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.id_lbl = QtWidgets.QLabel(parent=OrderFrame)
        font = QtGui.QFont()
        font.setBold(True)
        self.id_lbl.setFont(font)
        self.id_lbl.setObjectName("id_lbl")
        self.verticalLayout.addWidget(self.id_lbl)
        self.status_lbl = QtWidgets.QLabel(parent=OrderFrame)
        self.status_lbl.setObjectName("status_lbl")
        self.verticalLayout.addWidget(self.status_lbl)
        self.address_lbl = QtWidgets.QLabel(parent=OrderFrame)
        self.address_lbl.setObjectName("address_lbl")
        self.verticalLayout.addWidget(self.address_lbl)
        self.date_lbl = QtWidgets.QLabel(parent=OrderFrame)
        self.date_lbl.setObjectName("date_lbl")
        self.verticalLayout.addWidget(self.date_lbl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.delivery_date_lbl = QtWidgets.QLabel(parent=OrderFrame)
        self.delivery_date_lbl.setObjectName("delivery_date_lbl")
        self.horizontalLayout.addWidget(self.delivery_date_lbl)

        self.retranslateUi(OrderFrame)
        QtCore.QMetaObject.connectSlotsByName(OrderFrame)

    def retranslateUi(self, OrderFrame):
        _translate = QtCore.QCoreApplication.translate
        OrderFrame.setWindowTitle(_translate("OrderFrame", "Frame"))
        self.id_lbl.setText(_translate("OrderFrame", "TextLabel"))
        self.status_lbl.setText(_translate("OrderFrame", "TextLabel"))
        self.address_lbl.setText(_translate("OrderFrame", "TextLabel"))
        self.date_lbl.setText(_translate("OrderFrame", "TextLabel"))
        self.delivery_date_lbl.setText(_translate("OrderFrame", "TextLabel"))
