# Form implementation generated from reading ui file 'ui/orderdialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OrderDialog(object):
    def setupUi(self, OrderDialog):
        OrderDialog.setObjectName("OrderDialog")
        OrderDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(OrderDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.id_lbl = QtWidgets.QLabel(parent=OrderDialog)
        self.id_lbl.setObjectName("id_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.id_lbl)
        self.id_edit = QtWidgets.QLineEdit(parent=OrderDialog)
        self.id_edit.setReadOnly(True)
        self.id_edit.setObjectName("id_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.id_edit)
        self.label_2 = QtWidgets.QLabel(parent=OrderDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.status_combo = QtWidgets.QComboBox(parent=OrderDialog)
        self.status_combo.setObjectName("status_combo")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.status_combo)
        self.label_3 = QtWidgets.QLabel(parent=OrderDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.client_combo = QtWidgets.QComboBox(parent=OrderDialog)
        self.client_combo.setObjectName("client_combo")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.client_combo)
        self.label_4 = QtWidgets.QLabel(parent=OrderDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.address_edit = QtWidgets.QLineEdit(parent=OrderDialog)
        self.address_edit.setObjectName("address_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address_edit)
        self.label_5 = QtWidgets.QLabel(parent=OrderDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.order_date = QtWidgets.QDateEdit(parent=OrderDialog)
        self.order_date.setCalendarPopup(True)
        self.order_date.setObjectName("order_date")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.order_date)
        self.label_6 = QtWidgets.QLabel(parent=OrderDialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.delivery_date = QtWidgets.QDateEdit(parent=OrderDialog)
        self.delivery_date.setCalendarPopup(True)
        self.delivery_date.setObjectName("delivery_date")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.delivery_date)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_btn = QtWidgets.QPushButton(parent=OrderDialog)
        self.cancel_btn.setDefault(True)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.save_btn = QtWidgets.QPushButton(parent=OrderDialog)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(OrderDialog)
        QtCore.QMetaObject.connectSlotsByName(OrderDialog)

    def retranslateUi(self, OrderDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderDialog.setWindowTitle(_translate("OrderDialog", "Dialog"))
        self.id_lbl.setText(_translate("OrderDialog", "ID заказа"))
        self.label_2.setText(_translate("OrderDialog", "Статус заказа *"))
        self.label_3.setText(_translate("OrderDialog", "Клиент *"))
        self.label_4.setText(_translate("OrderDialog", "Адрес пункта выдачи *"))
        self.address_edit.setPlaceholderText(_translate("OrderDialog", "Индекс, Город, Улица, Дом"))
        self.label_5.setText(_translate("OrderDialog", "Дата заказа *"))
        self.label_6.setText(_translate("OrderDialog", "Дата доставки *"))
        self.cancel_btn.setText(_translate("OrderDialog", "Отмена"))
        self.save_btn.setText(_translate("OrderDialog", "Сохранить"))
