# Form implementation generated from reading ui file 'ui/productframe.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProductFrame(object):
    def setupUi(self, ProductFrame):
        ProductFrame.setObjectName("ProductFrame")
        ProductFrame.resize(344, 190)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ProductFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.img_lbl = QtWidgets.QLabel(parent=ProductFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_lbl.sizePolicy().hasHeightForWidth())
        self.img_lbl.setSizePolicy(sizePolicy)
        self.img_lbl.setMinimumSize(QtCore.QSize(180, 150))
        self.img_lbl.setMaximumSize(QtCore.QSize(180, 150))
        self.img_lbl.setText("")
        self.img_lbl.setObjectName("img_lbl")
        self.horizontalLayout.addWidget(self.img_lbl, 0, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_cat_lbl = QtWidgets.QLabel(parent=ProductFrame)
        font = QtGui.QFont()
        font.setBold(True)
        self.name_cat_lbl.setFont(font)
        self.name_cat_lbl.setObjectName("name_cat_lbl")
        self.verticalLayout.addWidget(self.name_cat_lbl)
        self.desc_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.desc_lbl.setObjectName("desc_lbl")
        self.verticalLayout.addWidget(self.desc_lbl)
        self.manuf_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.manuf_lbl.setObjectName("manuf_lbl")
        self.verticalLayout.addWidget(self.manuf_lbl)
        self.supplier_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.supplier_lbl.setObjectName("supplier_lbl")
        self.verticalLayout.addWidget(self.supplier_lbl)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.price_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.price_lbl.setObjectName("price_lbl")
        self.horizontalLayout_2.addWidget(self.price_lbl, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.unit_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.unit_lbl.setObjectName("unit_lbl")
        self.verticalLayout.addWidget(self.unit_lbl)
        self.stock_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.stock_lbl.setObjectName("stock_lbl")
        self.verticalLayout.addWidget(self.stock_lbl)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.discount_lbl = QtWidgets.QLabel(parent=ProductFrame)
        self.discount_lbl.setObjectName("discount_lbl")
        self.horizontalLayout.addWidget(self.discount_lbl, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)

        self.retranslateUi(ProductFrame)
        QtCore.QMetaObject.connectSlotsByName(ProductFrame)

    def retranslateUi(self, ProductFrame):
        _translate = QtCore.QCoreApplication.translate
        ProductFrame.setWindowTitle(_translate("ProductFrame", "Frame"))
        self.name_cat_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.desc_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.manuf_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.supplier_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.price_lbl.setText(_translate("ProductFrame", "Цена: "))
        self.unit_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.stock_lbl.setText(_translate("ProductFrame", "TextLabel"))
        self.discount_lbl.setText(_translate("ProductFrame", "TextLabel"))
